/**
 * Preset Templates for ZZZ Poster Studio (v2.5 Specification)
 * Decoupled from platform/social media names.
 * Standard clean typography: Noto Sans SC / System Sans.
 * Pure composition: High-quality backgrounds (gradients/popdots/film/textures), text, and stickers (no shape layers).
 */
window.ZZZ_TEMPLATES = [
  {
    id: 'template_guide_16_9',
    name: '16:9 标准横版 (新艾利都冒险指南)',
    category: '16:9 宽屏画幅',
    width: 1920,
    height: 1080,
    background: {
      type: 'gradient',
      color: '#0f172a',
      gradient: {
        type: 'linear',
        angle: 135,
        color1: '#0f172a',
        color2: '#1e293b'
      },
      popdots: null,
      film: null,
      decoration: {
        type: 'cybergrid',
        color: '#38bdf8',
        opacity: 0.25,
        scale: 1
      },
      image: null,
      imageSrc: null,
      imageFit: 'cover',
      blur: 0,
      overlayOpacity: 0.15
    },
    layers: [
      {
        id: 'text_tag',
        type: 'text',
        name: '顶部标签',
        text: '绝区零 · 全新版本前瞻',
        x: 480,
        y: 260,
        width: 600,
        height: 80,
        rotation: 0,
        fontSize: 40,
        fontWeight: 'bold',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#38bdf8',
        strokeColor: 'transparent',
        strokeWidth: 0,
        bgFill: 'rgba(56, 189, 248, 0.15)',
        bgRadius: 18,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_main_title',
        type: 'text',
        name: '主标题',
        text: '新艾利都冒险指南',
        x: 580,
        y: 430,
        width: 820,
        height: 140,
        rotation: -2,
        fontSize: 92,
        fontWeight: '900',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#ffffff',
        strokeColor: '#0f172a',
        strokeWidth: 8,
        shadowType: 'glow',
        shadowColor: 'rgba(56, 189, 248, 0.6)',
        shadowBlur: 24,
        align: 'left',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_subtitle',
        type: 'text',
        name: '副标题',
        text: '新手必看！角色养成与阵容搭配全解析',
        x: 580,
        y: 590,
        width: 820,
        height: 70,
        rotation: 0,
        fontSize: 36,
        fontWeight: '600',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#cbd5e1',
        strokeColor: 'transparent',
        strokeWidth: 0,
        align: 'left',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'sticker_hero',
        type: 'sticker',
        name: '安比 疑惑',
        src: '../assets/emojis_hd/Sticker Set 1 Anby doubt.png',
        x: 1420,
        y: 540,
        width: 520,
        height: 520,
        rotation: 6,
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'sticker_sub',
        type: 'sticker',
        name: '比利 完成',
        src: '../assets/emojis_hd/Sticker Set 1 Billy finish.png',
        x: 1100,
        y: 720,
        width: 320,
        height: 320,
        rotation: -8,
        opacity: 1,
        visible: true,
        locked: false
      }
    ]
  },
  {
    id: 'template_comic_4_3',
    name: '4:3 经典横版 (狡兔屋美漫复古特刊)',
    category: '4:3 经典画幅',
    width: 1600,
    height: 1200,
    background: {
      type: 'popdots',
      color: '#ffffff',
      popdots: {
        bgColor: '#ffffff',
        dotColor: '#0f172a',
        pattern: 'micro',
        dotRadius: 3,
        dotSpacing: 12,
        opacity: 0.95
      },
      film: null,
      decoration: {
        type: 'speedlines',
        color: '#18181b',
        opacity: 0.1,
        scale: 1
      },
      image: null,
      imageSrc: null,
      imageFit: 'cover',
      blur: 0,
      overlayOpacity: 0
    },
    layers: [
      {
        id: 'text_comic_top',
        type: 'text',
        name: '特刊标号',
        text: 'CUNNING HARES COMIC ISSUE // VOL.04',
        x: 800,
        y: 140,
        width: 900,
        height: 50,
        rotation: 0,
        fontSize: 26,
        fontWeight: '900',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#18181b',
        strokeColor: 'transparent',
        strokeWidth: 0,
        bgFill: 'rgba(255, 255, 255, 0.9)',
        bgRadius: 14,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_comic_title',
        type: 'text',
        name: '波普网点大标题',
        text: '狡兔屋日常事件簿',
        x: 520,
        y: 350,
        width: 800,
        height: 140,
        rotation: -2,
        fontSize: 84,
        fontWeight: '900',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#ffffff',
        strokeColor: '#18181b',
        strokeWidth: 9,
        shadowType: 'halftone',
        halftoneType: 'dots',
        shadowColor: '#334155',
        shadowOffset: 10,
        halftoneSpacing: 6,
        align: 'left',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_comic_desc',
        type: 'text',
        name: '副标题委托标语',
        text: '「 承接新艾利都一切高额委托，丁尼即刻结清！ 」',
        x: 520,
        y: 480,
        width: 780,
        height: 60,
        rotation: 0,
        fontSize: 28,
        fontWeight: '700',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#ffffff',
        strokeColor: '#18181b',
        strokeWidth: 4,
        align: 'left',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'sticker_nicole',
        type: 'sticker',
        name: '妮可 得意',
        src: '../assets/emojis_hd/Sticker Set 1 Nicole smirk.png',
        x: 1200,
        y: 530,
        width: 520,
        height: 520,
        rotation: 4,
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'sticker_billy',
        type: 'sticker',
        name: '比利 完成',
        src: '../assets/emojis_hd/Sticker Set 1 Billy finish.png',
        x: 880,
        y: 770,
        width: 420,
        height: 420,
        rotation: -6,
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_comic_badge',
        type: 'text',
        name: '底部胶囊提示',
        text: '录像带租赁与以太适性检测中',
        x: 520,
        y: 980,
        width: 600,
        height: 70,
        rotation: 0,
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#ffffff',
        strokeColor: 'transparent',
        strokeWidth: 0,
        bgFill: '#18181b',
        bgRadius: 20,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      }
    ]
  },
  {
    id: 'template_diary_3_4',
    name: '3:4 经典竖版 (元气漫步图文)',
    category: '3:4 竖版画幅',
    width: 1080,
    height: 1440,
    background: {
      type: 'gradient',
      color: '#fff1f2',
      gradient: {
        type: 'linear',
        angle: 180,
        color1: '#fff1f2',
        color2: '#fce7f3'
      },
      popdots: null,
      film: null,
      decoration: {
        type: 'none',
        color: '#ffffff',
        opacity: 0.35,
        scale: 1
      },
      image: null,
      imageSrc: null,
      imageFit: 'cover',
      blur: 0,
      overlayOpacity: 0
    },
    layers: [
      {
        id: 'text_top_badge',
        type: 'text',
        name: '顶部小标',
        text: 'RIDU STROLL · 丽都漫步',
        x: 540,
        y: 200,
        width: 500,
        height: 60,
        rotation: 0,
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#e11d48',
        strokeColor: 'transparent',
        strokeWidth: 0,
        bgFill: 'rgba(225, 29, 72, 0.1)',
        bgRadius: 16,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_diary_title',
        type: 'text',
        name: '卡片大标题',
        text: '今天也是超元气的一天！',
        x: 540,
        y: 320,
        width: 860,
        height: 120,
        rotation: 0,
        fontSize: 58,
        fontWeight: '900',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#1e293b',
        strokeColor: 'transparent',
        strokeWidth: 0,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'sticker_center',
        type: 'sticker',
        name: '安比 丽都漫步',
        src: '../assets/emojis_hd/Zenless Zone Zero Ridu Stroll Sticker Pack 1 Anby.png',
        x: 540,
        y: 720,
        width: 680,
        height: 680,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_bottom_note',
        type: 'text',
        name: '底部提示语',
        text: '附送独家美味汉堡点餐秘籍',
        x: 540,
        y: 1180,
        width: 700,
        height: 70,
        rotation: 0,
        fontSize: 32,
        fontWeight: '600',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#f43f5e',
        strokeColor: 'transparent',
        strokeWidth: 0,
        bgFill: '#ffffff',
        bgRadius: 24,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      }
    ]
  },
  {
    id: 'template_avatar_1_1',
    name: '1:1 正方画幅 (邦布活力出击头像)',
    category: '1:1 正方画幅',
    width: 1080,
    height: 1080,
    background: {
      type: 'gradient',
      color: '#fef08a',
      gradient: {
        type: 'radial',
        angle: 0,
        color1: '#fef08a',
        color2: '#f59e0b'
      },
      popdots: null,
      film: null,
      decoration: {
        type: 'none',
        color: '#ffffff',
        opacity: 0.35,
        scale: 1
      },
      image: null,
      imageSrc: null,
      imageFit: 'cover',
      blur: 0,
      overlayOpacity: 0
    },
    layers: [
      {
        id: 'sticker_bangboo',
        type: 'sticker',
        name: '伊埃斯 活力登场',
        src: '../assets/emojis_hd/En-Nah Stroll Sticker Pack 1 Ta-da!.png',
        x: 540,
        y: 490,
        width: 720,
        height: 720,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_bangboo_title',
        type: 'text',
        name: '底部口号',
        text: 'EN-NAH! 活力满分',
        x: 540,
        y: 920,
        width: 600,
        height: 80,
        rotation: 0,
        fontSize: 48,
        fontWeight: '900',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#b45309',
        strokeColor: '#ffffff',
        strokeWidth: 6,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      }
    ]
  },
  {
    id: 'template_wallpaper_9_16',
    name: '9:16 满屏竖版 (星见雅机能壁纸)',
    category: '9:16 竖版画幅',
    width: 1080,
    height: 1920,
    background: {
      type: 'gradient',
      color: '#18181b',
      gradient: {
        type: 'linear',
        angle: 160,
        color1: '#18181b',
        color2: '#312e81'
      },
      popdots: null,
      film: null,
      decoration: {
        type: 'cybergrid',
        color: '#818cf8',
        opacity: 0.3,
        scale: 1
      },
      image: null,
      imageSrc: null,
      imageFit: 'cover',
      blur: 0,
      overlayOpacity: 0.1
    },
    layers: [
      {
        id: 'text_wall_top',
        type: 'text',
        name: '顶栏时间标题',
        text: 'NEW ERIDU // 07:30',
        x: 540,
        y: 280,
        width: 600,
        height: 60,
        rotation: 0,
        fontSize: 32,
        fontWeight: 'bold',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#a5b4fc',
        strokeColor: 'transparent',
        strokeWidth: 0,
        align: 'center',
        opacity: 0.9,
        visible: true,
        locked: false
      },
      {
        id: 'text_wall_huge',
        type: 'text',
        name: '背景水印字',
        text: 'SECTION 6',
        x: 540,
        y: 650,
        width: 900,
        height: 160,
        rotation: -90,
        fontSize: 140,
        fontWeight: '900',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: 'rgba(255,255,255,0.06)',
        strokeColor: 'transparent',
        strokeWidth: 0,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: true
      },
      {
        id: 'sticker_miyabi',
        type: 'sticker',
        name: '星见雅 雷蛇特辑',
        src: "../assets/emojis_hd/Miyabi's Razer emoji pack 6.png",
        x: 540,
        y: 1040,
        width: 860,
        height: 860,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false
      },
      {
        id: 'text_wall_bottom',
        type: 'text',
        name: '底部签名',
        text: '「 斩断空洞之刃，守护新艾利都 」',
        x: 540,
        y: 1650,
        width: 800,
        height: 60,
        rotation: 0,
        fontSize: 34,
        fontWeight: '600',
        fontFamily: "'Noto Sans SC', sans-serif",
        fillColor: '#e0e7ff',
        strokeColor: 'transparent',
        strokeWidth: 0,
        align: 'center',
        opacity: 1,
        visible: true,
        locked: false
      }
    ]
  }
];
